### ISSUE TITLE
SLATE client v1.0.31 doesn't work on macOS < 12.0

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#313]
From @jlstephen on Slack:

looks like the newest slate client for macos doesn't work for < 12.0
```shell
$ slate version
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /usr/local/bin/slate (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /usr/local/bin/slate
Abort trap: 6
```
running macos 11.7

**Comment by adamhgriffith-uofu** [comment]
Asked the group whether or not we should compile two macOS SLATE clients. @LincolnBryant supports trying that route.
